server:
  port: 8080

spring:
  datasource:
    username: root
    password: kevinavy@123
    url: jdbc:mysql://47.118.117.34:3306/competition_sys?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
